title = "Syrym Tussupbekov"
baseURL = "https://syrym.pro"
theme = "researcher"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]
enableEmoji = true
math = false  # enable KaTeX (https://katex.org/) globally

[params]
  author = "Syrym Tussupbekov"
  description = "Personal website"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "Syrym Tussupbekov"
    url = "https://github.com/HimekoInaba"

[permalinks]
  "/" = "/:filename"

[menu]
#  [[menu.main]]
#    name = "About"
#    url = "/about"
#    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    weight = 1
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
